In [1]:
import os
import pandas as pd

os.chdir('/store/carroll/sbgplants/')

In [2]:
# file paths
raw = 'data/raw'
doi = os.path.join(raw, '10.15485.1618130') # Locations, metadata, and species cover from field sampling survey associated with NEON AOP survey, East River, CO 2018

out_folder = 'data/out_csv'

table = 'species_list'

In [8]:
# load relevant raw tables
# fractional_cover = pd.read_csv(os.path.join(doi, 'fractional_cover.csv'))
sample = pd.read_csv(os.path.join(out_folder, 'sample.csv'))

species_list = pd.read_csv(os.path.join(doi, 'species_list.csv'))
species_list = species_list.dropna(axis=1, how='all').dropna(axis=0, how='all') # drop all na rows and columns
species_list

,CoverCode,Family,Genus,Species,AltFieldCode,Notes
0,AcoRos,Rosaceae,Acomastylis,rossii,GeuRos,*syn. = Geum rossii
1,AgaUrt,Lamiaceae,Agastache,urticifolia,NaN,NaN
2,AgrSpp,Poaceae,Agrostis,spp,NaN,NaN
3,Alder,Betulaceae,Alnus,incana,NaN,NaN
4,AneMul,Ranunculaceae,Anemone,multifida,NaN,NaN
...,...,...,...,...,...,...
102,VicAme,Fabaceae,Vicia,americana,NaN,NaN
103,Willow,Salicaceae,Salix,spp,NaN,NaN
104,wolfii,Salicaceae,Salix,wolfii,NaN,NaN
105,WyeAmp,Asteraceae,Wyethia,amplexicaulis,NaN,NaN
106,WyeSpp,Asteraceae,Wyethia,spp,NaN,NaN

In [12]:
# prepare & populate out table
out_table = pd.DataFrame(index=range(len(species_list)))

out_table['species_or_type'] = species_list['Genus'] + ' ' + species_list['Species']
out_table.loc[out_table['species_or_type'].isna(), 'species_or_type'] = species_list.loc[species_list['Genus'].isna(), 'CoverCode']

out_table['family'] = species_list['Family']
out_table['genus'] = species_list['Genus']
out_table['species'] = species_list['Species']
out_table['lifeform_code'] =None

out_table

,species_or_type,family,genus,species,lifeform_code
0,Acomastylis rossii,Rosaceae,Acomastylis,rossii,None
1,Agastache urticifolia,Lamiaceae,Agastache,urticifolia,None
2,Agrostis spp,Poaceae,Agrostis,spp,None
3,Alnus incana,Betulaceae,Alnus,incana,None
4,Anemone multifida,Ranunculaceae,Anemone,multifida,None
...,...,...,...,...,...
102,Vicia americana,Fabaceae,Vicia,americana,None
103,Salix spp,Salicaceae,Salix,spp,None
104,Salix wolfii,Salicaceae,Salix,wolfii,None
105,Wyethia amplexicaulis,Asteraceae,Wyethia,amplexicaulis,None
106,Wyethia spp,Asteraceae,Wyethia,spp,None

In [14]:
# export table
fp_out = os.path.join(out_folder, f'{table}.csv')
out_table.to_csv(fp_out, index=False)